Use database helpers from mariadb-operator/api
openstack-k8s-operators/telemetry-operator pull request #201
Opened 2023-10-06 18:29 UTC by vyzigold

The database helpers got moved from lib-common to mariadb-operator to deal with circular dependencies: https://github.com/openstack-k8s-operators/lib-common/pull/352

2023-10-09 07:43 UTC, jlarriba requested changes

2023-10-09 07:43 UTC, jlarriba commented on go.mod
> +	github.com/openstack-k8s-operators/mariadb-operator/api v0.3.0
We should not be fixing into a version, use the latest v0.1.1-0 as with the rest of the operators, like it is being done here: https://github.com/openstack-k8s-operators/mariadb-operator/blob/main/go.mod#L10

2023-10-10 07:55 UTC, jlarriba commented on go.mod
> +	github.com/openstack-k8s-operators/mariadb-operator/api v0.3.0
yes, this is the behavior we are seeing. I think we could just go with the latest tag as that's default behaviour for go mod.

2023-10-10 08:55 UTC, gibizer commented on go.mod
> +	github.com/openstack-k8s-operators/mariadb-operator/api v0.3.0
Yeah, I think this is OK to land. Renovate will bump over 0.3.0 with a pseudoversion when there is a newer commit

2023-10-10 09:08 UTC, jlarriba approved these changes

2023-10-10 09:12 UTC, merged