Rewrite telemetry resource
openstack-k8s-operators/telemetry-operator pull request #240
Opened 2023-11-20 10:46 UTC by vyzigold

Rewrite the telemetry resource to use a similar pattern to the openstack control plane resource. The telemetry resource is an umbrela resource for other telemetry related resources, which for right now are "ceilometer" and "autoscaling". These resources can be enabled and customized by using the "enabled" and "template" fields similarly to how openstack services are enabled and customized in the openstack control plane CR.

The "secret" field in the telemetry resource can be used to set the "secret" fields for both ceilometer and autoscaling.

The autoscaling is disabled by default and ceilometer is enabled by default.

Look at the config/samples/telemetry_v1beta1_telemetry.yaml for an example CR.

2023-11-20 11:15 UTC, jlarriba requested changes

2023-11-20 11:15 UTC, jlarriba commented on api/v1beta1/telemetry_types.go
> +	Template CeilometerSpec `json:"template,omitempty"`
To avoid having to redeclare "template:", this should be an inline attribute:
```
CeilometerSpec `json:",omitempty"`
```

In the same way as, for example, Cinder is doing:

https://github.com/openstack-k8s-operators/cinder-operator/blob/main/api/v1beta1/cinderapi_types.go#L54

2023-11-20 11:15 UTC, jlarriba commented on config/samples/telemetry_v1beta1_telemetry.yaml
> +    template:
if we use inline declaration in the telemetry_types, this would be:

```
spec:
  ceilometer:
     enabled: true
     secret: osp-secret
...
```

for better readability.

2023-11-20 11:15 UTC, jlarriba commented on config/samples/telemetry_v1beta1_telemetry.yaml
> +      secret: osp-secret
If we deploy the secret in telemetry, we do not declare it in ceilometer.

2023-11-20 11:15 UTC, jlarriba commented on tests/kuttl/suites/default/tests/01-deploy.yaml
> +    template:
Same as above, spare the "template" declaration.

2023-11-20 11:15 UTC, jlarriba commented on tests/kuttl/suites/default/tests/01-deploy.yaml
> +    template:
Same as above, spare the template declaration

2023-11-20 11:15 UTC, jlarriba commented on config/samples/telemetry_v1beta1_telemetry.yaml
> +    template:
Same as explained for ceilometer.

2023-11-20 14:02 UTC, vyzigold commented on api/v1beta1/telemetry_types.go
> +	Template CeilometerSpec `json:"template,omitempty"`
I see your point and I'm not against it. The reason why I did it like this is, that I thought, that users would already be familiar with the openstack control plane CR and my goal was to make the telemetry resource similar to that. In the openstack control plane you'd have:
```
service_name:
  enabled: true or false
  template:
    <the service CR>
service_name2:
  ...
```
Which is what I have here right now. I wonder why cinder decided to go a different way and which of the operators we should follow.

2023-11-20 14:13 UTC, vyzigold commented
/retest

2023-11-20 15:13 UTC, jlarriba commented on api/v1beta1/telemetry_types.go
> +	Template CeilometerSpec `json:"template,omitempty"`
All service operators follow the same pattern. Cinder was just an example. The template explicit field is only used in openstack-operator.

2023-11-20 15:24 UTC, vyzigold commented on api/v1beta1/telemetry_types.go
> +	Template CeilometerSpec `json:"template,omitempty"`
Alright, I'll change it then.

2023-11-21 13:52 UTC, vyzigold commented
/retest

2023-11-21 16:24 UTC, merged