[zuul] Add a job to check operator errors
openstack-k8s-operators/telemetry-operator pull request #353
Opened 2024-03-25 07:58 UTC by vyzigold

This checks for errors in the operator logs.

For testing purposes I introduced an error in the metricstorage controller, so the job should fail right now.

2024-03-25 15:35 UTC, elfiesmelfie requested changes

2024-03-25 15:35 UTC, elfiesmelfie commented on zuul.d/projects.yaml
> +    name: telemetry-operator-multinode-check-errors
The job name should be updated and the description added.

This job tests the expected default deployment of telemetry-operator i.e. telemetry enabled, metricsstorage enabled, no coo.
We want to make sure that the failure is graceful, rather than throwing an exception.

The name should be something like `telemetry-operator-multinode-default-telemetry` or something like that.
The description should include that we are testing the default behaviour, and making sure that metricsStorage fails gracefully and waits for COO if it is not installed.

2024-03-25 15:35 UTC, elfiesmelfie commented on ci/vars-check-errors.yml
> +cifmw_run_test_role: test_operator
I don't think this is needed.

You're not using the test_operator is used to run either tempest or tobiko (https://github.com/openstack-k8s-operators/ci-framework/blob/8d9bbe7c7cbba3eb900263d03f9d59e3203b1951/docs/source/usage/01_usage.md?plain=1#L44)
The default is to run tempest via test_operator. 
In this case, the tempest tests would not be useful, since the default config would run all the tests from core tempest, rather than from tempest-plugins.
https://github.com/openstack-k8s-operators/ci-framework/blob/8d9bbe7c7cbba3eb900263d03f9d59e3203b1951/roles/test_operator/README.md
The cifmw_test_operator_tempest_container defaults to openstack-tempest, which installs the tempest package, but not the tempest plugins from the `openstack-tempest-all` package, which includes telemetry-tempest-plugin.

Even if you configure tempest to run, I think there's going to be only one or two that work, since only  ceilometer and sg_core will be available.

2024-03-25 15:35 UTC, elfiesmelfie commented on ci/check-errors.yml
> +---
Based on the other comments, this should be renamed, and also check for expected behaviour. 

e.g. Does the MetricStorage report the right status?

2024-03-26 06:21 UTC, vyzigold commented on ci/check-errors.yml
> +---
MetricStorage shouldn't get deployed in this scenario, so there is nothing to check (the operator can still fail though). But I'll check the status of telemetry. Thanks.

2024-03-26 07:09 UTC, jlarriba commented on ci/check-errors.yml
> +---
I believe that MetricStorage should get deployed in this scenario, because that way we will be not only detecting the error you are trying here (that we added an Owns over a COO API), but also test that MetricStorage fails gracefully without bringing the whole operator down. This test case should test those two things at once, instead of only one of them.

2024-03-26 07:12 UTC, vyzigold commented on ci/check-errors.yml
> +---
Alright, I'll try to add MetricStorage to the deployment.

2024-03-26 07:13 UTC, vyzigold commented on zuul.d/projects.yaml
> +    name: telemetry-operator-multinode-check-errors
I'm not sure what you mean by the "graceful failure". I guess I shouldn't use the `ansible.builtin.fail`? What are the alternatives then?

2024-03-26 07:59 UTC, vyzigold commented on ci/check-errors.yml
> +---
While I was at it, I also enabled autoscaling, so we can deploy the whole telemetry. I am a little unsure about enabling MetricStorage though. In my opinion, if COO isn't installed, then MetricStorage shouldn't get to a Ready state. That means Telemetry won't get to Ready state and I think because of that the control-plane won't get to the ready state and the deployment won't be successful. But lets see what the CI thinks about this first.

2024-03-26 10:11 UTC, vyzigold commented
cert-manager issues. I've seen that on another PR as well.

2024-03-26 13:11 UTC, vyzigold commented on ci/vars-default-telemetry.yml
> +              autoscaling:
We've discussed this with Juan in slack today, you can take a look for the details there. I think we settled on the idea to enable the whole telemetry without COO and check the logs and CR status fields in detail to verify everything is as expected - the operator is running, ceilometer is ready, metric storage isn't ready, but reports the correct statuses and is trying to look for COO.

Adding autoscaling to the deployment probably doesn't add much at the moment. We'd basically just check, that it's ready. But I don't think it hurts us in any way.

2024-03-26 13:14 UTC, vyzigold commented on ci/default-telemetry.yml
> +---
I wasn't completely sure about the naming this morning, but I ended up following what I thought you're suggesting :D . But I guess if we have a "vars-default-telemetry.yml" and "check-default-telemetry.yml", we could then be adding other "something-default-telemetry.yml" when we see the need. That makes sense.

2024-03-27 14:19 UTC, vyzigold commented
recheck

2024-03-27 19:51 UTC, vyzigold commented
Just as I worried. The test failed. CI framework didn't execute our tests because control plane wasn't ready because telemetry wasn't ready because metric-storage wasn't ready which is caused by missing COO. I'll temporarily disable metric-storage to see if the rest works OK and if CI framework executes our tests.

2024-03-28 13:47 UTC, vyzigold commented
recheck
It doesn't seem like it triggered for some reason.

2024-03-28 14:35 UTC, elfiesmelfie commented
> Just as I worried. The test failed. CI framework didn't execute our tests because control plane wasn't ready because telemetry wasn't ready because metric-storage wasn't ready which is caused by missing COO. I'll temporarily disable metric-storage to see if the rest works OK and if CI framework executes our tests.

You can also add the check playbook to [Zuul's post-run config](https://zuul-ci.org/docs/zuul/latest/config/job.html#attr-job.post-run) while you're debugging and fixing the issue. 
You can leave the playbook as a hook, but also add it as a post-run playbook temporarily, which will always be executed in a job, and help to debug and verify any fixes you put in.

2024-04-03 08:30 UTC, vyzigold commented
It's waiting for heat to get ready. We need to wait until a bug in heat is fixed.

2024-04-11 05:48 UTC, vyzigold commented
recheck

2024-04-11 16:26 UTC, elfiesmelfie commented
> Build failed (check pipeline). Post `recheck` (without leading slash) to rerun all jobs. Make sure the failure cause has been resolved before you rerun jobs.
> 
> https://review.rdoproject.org/zuul/buildset/178dc9387a44478bbfe6ebbd9068dfa8
> 
> ✔️ [openstack-k8s-operators-content-provider ](https://review.rdoproject.org/zuul/build/3c0dd576baa34b829801ac98029ff485) SUCCESS in 1h 56m 54s ✔️ [podified-multinode-edpm-deployment-crc ](https://review.rdoproject.org/zuul/build/07b78ad49a454a1faddcdc5b5bc4049b) SUCCESS in 1h 14m 54s ❌ [telemetry-operator-multinode-autoscaling-tempest ](https://review.rdoproject.org/zuul/build/c928a55166974bbb8845e8c99b008472) **FAILURE** in 1h 33m 48s ✔️ [telemetry-operator-multinode-default-telemetry ](https://review.rdoproject.org/zuul/build/33b88be10b9c4b0d8549b2b765e9571d) SUCCESS in 1h 11m 04s

The failure is due to the (memcached instance not being provisioned)[https://logserver.rdoproject.org/53/353/f0772c3da4fe5f88b32f96ee5c21baf2309c4806/github-check/telemetry-operator-multinode-autoscaling-tempest/c928a55/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/autoscalings.telemetry.openstack.org/autoscaling.yaml].
The spec.aodh.memcachedInstance = "" i.e. it is not being set.

Previously (see [here](https://logserver.rdoproject.org/53/353/f0772c3da4fe5f88b32f96ee5c21baf2309c4806/github-check/telemetry-operator-multinode-autoscaling-tempest/ca9b0de/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/autoscalings.telemetry.openstack.org/autoscaling.yaml)), the instance was set to `memcached`. There's also a bunch of other differences in the config, including the spec.aodh.override being set previously, but not now.

2024-04-12 06:01 UTC, vyzigold commented
Hmm, that's strange. telemetry-operator-multinode-autoscaling-tempest isn't really something I'd normally care on this PR at the moment. But memcached not being set almost seems like we may have some kind of bug somewhere :thinking:

2024-04-12 11:38 UTC, elfiesmelfie commented
> Hmm, that's strange. telemetry-operator-multinode-autoscaling-tempest isn't really something I'd normally care on this PR at the moment. But memcached not being set almost seems like we may have some kind of bug somewhere 🤔

Definitely a bug somewhere, I saw this issue earlier in the week, and Marihan is also seeing it here: https://github.com/openstack-k8s-operators/telemetry-operator/pull/353

2024-04-19 14:47 UTC, elfiesmelfie commented
> Build failed (check pipeline). Post `recheck` (without leading slash) to rerun all jobs. Make sure the failure cause has been resolved before you rerun jobs.
> 
> https://review.rdoproject.org/zuul/buildset/ccfeaddc341b429eae31f29d445a0f3e
> 
> ✔️ [openstack-k8s-operators-content-provider ](https://review.rdoproject.org/zuul/build/110df85772364107a5e19fff6f27d3c5) SUCCESS in 1h 55m 26s ✔️ [podified-multinode-edpm-deployment-crc ](https://review.rdoproject.org/zuul/build/026eaa454797418bae35fd38230ec668) SUCCESS in 1h 11m 43s ❌ [telemetry-operator-multinode-autoscaling-tempest ](https://review.rdoproject.org/zuul/build/be38d12e9fd84df3ad7e494ec3d9ac0d) **FAILURE** in 1h 33m 24s ✔️ [telemetry-operator-multinode-default-telemetry ](https://review.rdoproject.org/zuul/build/03652bdab981485f942d77129b60b5ee) SUCCESS in 1h 09m 27s

The failure was due to spec.aodh.memcachedInstance == ''. This issue has been resolved.

2024-04-19 14:47 UTC, elfiesmelfie commented
recheck

2024-04-25 07:50 UTC, vyzigold commented
I rewrote most of the ansible, so I squashed it and rebased on top of main.

2024-04-25 15:52 UTC, elfiesmelfie commented
recheck

2024-04-26 06:16 UTC, vyzigold commented
recheck
POST_FAILURE

2024-04-26 09:02 UTC, vyzigold commented
I forgot that I deliberately included a bug in the PR. I can confirm, that the job successfully detected the operator restarting.

2024-04-26 12:08 UTC, vyzigold commented
The autoscaling tempest job is failing because of `No resources found in openshift-operators namespace.` This isn't related to this PR.

2024-05-17 10:09 UTC, jlarriba commented
/lgtm

Awesome work done here!

2024-05-17 11:21 UTC, merged