Cleanup dashboards on disable/delete
openstack-k8s-operators/telemetry-operator pull request #399
Opened 2024-05-30 21:40 UTC by csibbitt

Cleans up these artifacts if dashboarding is disabled or the telemetry object is deleted:

- PrometheusRules
- Datasource definition
- Dashboard definitions

Since the UIPlugin object is a singleton we will not remove it in case there are other users.

2024-05-30 21:41 UTC, csibbitt commented
## Testing

First I enabled dashboarding
```
$ oc patch openstackcontrolplane openstack-galera-network-isolation --type='json' -p='[{"op": "replace", "path": "/spec/telemetry/template/metricStorage/monitoringStack/dashboardsEnabled", "value":true}]'

openstackcontrolplane.core.openstack.org/openstack-galera-network-isolation patched
```

All of the objects get created
```
$ oc get -n openstack PrometheusRule.monitoring.rhobs metric-storage
NAME             AGE
metric-storage   2m45s

$ oc get configmap -n openshift-config-managed | grep openstack
grafana-dashboard-openstack-cloud                     1      3m52s
grafana-dashboard-openstack-node                      1      3m52s
grafana-dashboard-openstack-vm                        1      3m52s
openstack-metric-storage-datasource                   2      3m52s
```

Then I disabled dashboarding
```
$ oc patch openstackcontrolplane openstack-galera-network-isolation --type='json' -p='[{"op": "replace", "path": "/spec/telemetry/template/metricStorage/monitoringStack/dashboardsEnabled", "value":false}]'

openstackcontrolplane.core.openstack.org/openstack-galera-network-isolation patched
```

All the objects go away
```
$ oc get -n openstack PrometheusRule.monitoring.rhobs metric-storage
Error from server (NotFound): prometheusrules.monitoring.rhobs "metric-storage" not found

$ oc get configmap -n openshift-config-managed | grep openstack
$
```

Re-enable and they come back
```
$ oc patch openstackcontrolplane openstack-galera-network-isolation --type='json' -p='[{"op": "replace", "path": "/spec/telemetry/template/metricStorage/monitoringStack/dashboardsEnabled", "value":true}]'

openstackcontrolplane.core.openstack.org/openstack-galera-network-isolation patched

$ oc get -n openstack PrometheusRule.monitoring.rhobs metric-storage
NAME             AGE
metric-storage   36s

$ oc get configmap -n openshift-config-managed | grep openstack
grafana-dashboard-openstack-cloud                     1      46s
grafana-dashboard-openstack-node                      1      46s
grafana-dashboard-openstack-vm                        1      46s
openstack-metric-storage-datasource                   2      46s
```

Finally, delete the entire telemetry and ensure they have gone away again

```
$ oc patch openstackcontrolplane openstack-galera-network-isolation --type='json' -p='[{"op": "replace", "path": "/spec/telemetry/enabled", "value":false}]'

openstackcontrolplane.core.openstack.org/openstack-galera-network-isolation patched

$ oc get -n openstack PrometheusRule.monitoring.rhobs metric-storage
Error from server (NotFound): prometheusrules.monitoring.rhobs "metric-storage" not found

$ oc get configmap -n openshift-config-managed | grep openstack
$
```

2024-06-05 14:01 UTC, paramite requested changes
One nit, otherwise this seems fine.

2024-06-05 14:01 UTC, paramite commented on controllers/metricstorage_controller.go
> +func (r *MetricStorageReconciler) deleteDashboardObjects(ctx context.Context, instance *telemetryv1.MetricStorage, helper *helper.Helper) (ctrl.Result, error) {
Since you don't need the `r` object in this method, I would rather move it to pkg/metricstorage as function.

2024-06-05 14:04 UTC, csibbitt commented on controllers/metricstorage_controller.go
> +func (r *MetricStorageReconciler) deleteDashboardObjects(ctx context.Context, instance *telemetryv1.MetricStorage, helper *helper.Helper) (ctrl.Result, error) {
Thanks, that makes sense.

2024-06-05 14:41 UTC, jlarriba reviewed
/lgtm

2024-06-11 13:03 UTC, merged